DEVICE: 'cpu'
LEARNING_RATE: 0.0002
TRAIN_DIR: 'data/train'
VAL_DIR: 'data/val'
BATCH_SIZE: 1
NUM_WORKERS: 2
IMAGE_SIZE: 1024
CHANNELS_IMG: 3
L1_LAMBDA: 100
LAMBDA_GP: 10
NUM_EPOCHS: 100
LOAD_MODEL: False
SAVE_MODEL: True
CHECKPOINT_DISC: 'disc.pth'
CHECKPOINT_GEN: 'gen.pth'




